#pragma once
#include <SFML/Graphics.hpp>

const int height = 64;
const int width = 64;


sf::String TileMap[height] = {
	"0000000000000000000000000000000000000000000000000000000000000000",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0           www                            www                 0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0                                                              0",
	"0000000000000000000000000000000000000000000000000000000000000000",
};